# Generated by Django 2.0.9 on 2025-09-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='p_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
