# Generated by Django 2.0.9 on 2025-10-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20251020_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatebatchuser',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dietplanes',
            name='day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dietplanes',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='healthdetails',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tips',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='join_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='pin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutvideo',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
