# Generated by Django 2.0.9 on 2025-10-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20251020_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='from_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='to_time',
            field=models.CharField(max_length=100),
        ),
    ]
