# Generated by Django 3.2.25 on 2026-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20251020_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
