# Generated by Django 3.2.25 on 2026-03-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutvideo',
            name='video',
            field=models.CharField(max_length=800),
        ),
    ]
